[pandoc]
args = [
    "--pdf-engine=xelatex",                                     # Использовать XeLaTeX как PDF-движок
    "--template=templates/eisvogel-custom_mephi_titlepage.tex", # Шаблон для оформления документа
    "--listings",                                               # Включить поддержку вставки кода в документе
    # "--lua-filter=filters/strikeout.lua",                     # Фильтр для зачёркивания текста
    # "--lua-filter=filters/underline.lua",                     # Фильтр для подчёркивания текста
    # "--lua-filter=filters/center-images.lua",                 # Фильтр для центрирования изображений (не нужен, если пишете на LaTeX и вставляете картинки через него)
    # "--lua-filter=filters/word-count.lua",                    # Фильтр для подсчёта слов в документе
    "--lua-filter=filters/pagebreak.lua",                       # Фильтр, позволяющий работать с BREAK__ (он его заменяет на \newpage)
    "--metadata-file=tmp/metadata.yaml",                        # Файл с метаданными
    "--citeproc",                                               # Включить обработку цитирований
    "--toc",                                                    # Включить оглавление
    "--toc-depth=2",                                            # Глубина оглавления
]
src = ["some document"]
out-name = "output.pdf"

[metadata.general]
title = "Название документа"
# subtitle = ""
# abstract = ""
author = ["автор"]
date = "осень 2024"
lang = "ru"

# Настройка самого pandoc. Подробнее https://pandoc.org/MANUAL.html#variables-for-latex

[metadata.layout]
block-headings = true # изменяет поведение заголовков
# classoption = "a4paper, 12pt, ..."                                         # опции класса документа
# documentclass = "scrartcl"                                                 # параметр класса документа
geometry = "left=2cm, right=2cm, top=2cm, bottom=2cm, footskip=5cm"          # поля страницы
# hyperrefoptions = "linktoc=all, pdfwindowui, pdfpagemode=FullScreen, ..."  # опции гиперссылок
indent = true                                                                # отступы в абзацах
linestretch = 1.5                                                            # межстрочный интервал

# margin-left = "2cm"     # отступ слева    #
# margin-right = "2cm"    # отступ справа   #  устанавливает поля, если geometry не используется
# margin-top = "2cm"      # отступ сверху   #  (в противном случае geometry переопределяет их).
# margin-bottom = "2cm"   # отступ снизу    #

# pagestyle = "plain"     # стиль страницы (plain, headings, empty для article). связано с колонтитулами
papersize = "a4"          # размер бумаги (a4, letter, ...)
# secnumdepth = 5         # глубина нумерации разделов
# beamerarticle = true    # использовать стиль beamerarticle. есть примечание из документации
# handout = true          # режим рукописи для презентаций. см. документацию

[metadata.fonts]
# fontenc = "T1"                   # кодировка шрифта
# fontfamily = "libertinus"        # семейство шрифтов для использования с pdflatex
# fontfamilyoptions = "osf, p, sc" # опции fontfamily
fontsize = "12pt"                  # размер шрифта для body text

# mainfont = true                   #
# sansfont = true                   #
# monofont = true                   #  семейства шрифтов для использования 
# mathfont = true                   #  с xelatex или lualatex
# CJKmainfont = true                #
# CJKsansfont = true                #
# CJKmonofont = true                #

# mainfontoptions = "..."           #
# sansfontoptions = "..."           #
# monofontoptions = "..."           #  
# mathfontoptions = "..."           # опции шрифтов
# CJKoptions = "..."                #
# luatexjapresetoptions = "..."     #

# mainfontfallback = [              #
#     "FreeSans:",                  #
#     "NotoColorEmoji:mode=harf",   #   Шрифты, которые следует попробовать,
# ]                                 #   если глиф не найден в mainfont, sansfont или monofont соответственно. 
# sansfontfallback = []             #   Это списки.
# monofontfallback = []             #   

# microtypeoptions = "..."          # опции пакета microtype

[metadata.fonts.babelfonts]             #
# chinese-hant = "Noto Serif CJK TC"    # см. документацию
# russian = "Noto Serif"                #

[metadata.links]
colorlinks = true        # добавить цвет к тексту ссылки; автоматически включается, если установлено любое из значений linkcolor, filecolor, citecolor, urlcolor или toccolor
# boxlinks = true        # добавить рамку к ссылкам (нет эффекта если colorlinks = true) 
linkcolor = "NavyBlue"   # цвет внутренних ссылок
filecolor = "magenta"    # цвет ссылок на файлы
citecolor = "violet"     # цвет ссылок на источники
urlcolor = "cyan"        # цвет ссылок на URL
toccolor = "black"       # цвет ссылок в оглавлении
links-as-notes = false   # отображать ссылки как сноски
urlstyle = "same"        # стиль ссылок на URL (same, tt, rm, sf)

[metadata.frontmatter]
# lof = true             # включить список рисунков
# lot = true             # включить список таблиц
# thanks = true          # включить благодарности
toc = true               # включить оглавление
toc-depth = 2            # глубина оглавления

[metadata.bibliography]
# biblatexoptions = []               # опции для пакета biblatex
# biblio-style = "alphabetic"        # стиль библиографии
# biblio-title = "Список литературы" # заголовок библиографии
bibliography = "references.bib"      # путь к файлу библиографии
# natbiboptions = []                 # опции для пакета natbib

# Настройка шаблона eisvogel. Подробнее https://github.com/enhuiz/eisvogel

[metadata.template.titlepage]
titlepage = true                            # включить титульную страницу
# titlepage-color = "FFFFFF"                # цвет фона титульной страницы
titlepage-text-color = "000000"             # цвет текста на титульной странице
# titlepage-rule-color = "000000"           # цвет линии на титульной странице
titlepage-rule-height = -1                  # высота линии на титульной странице
# titlepage-background = "titlepage.pdf"    # фон для титульной страницы
titlepage-logo = "logo.jpeg"                # логотип для титульной страницы
logo-width = "35mm"                         # ширина логотипа

[metadata.template.page-background]
# page-background = "page-background.pdf"   # фон для всех страниц
# page-background-opacity = 0.5             # прозрачность фона

[metadata.template.toc]
toc-own-page = true                         # оглавление на отдельной странице

[metadata.template.figure]
# float-placement-figure = "H"              # местоположение рисунков

[metadata.template.table]
# table-use-row-colors = true               # использовать цвета строк в таблицах

[metadata.template.listings]
listings-no-page-break = true               # запрет разрыва страниц в блоках кода
listings-disable-line-numbers = true        # отключение нумерации строк в блоках кода
# code-block-font-size = "footnotesize"     # размер шрифта в блоках кода

[metadata.template.caption]
caption-justification = "centering"         # Выравнивание подписей к рисункам или таблицам по центру

[metadata.template.footnotes]
footnotes-pretty = true                     # Настройка сносок
# footnotes-disable-backlinks = true        # Отключение обратных ссылок в сносках

[metadata.template.headerandfooter]
# disable-header-and-footer = true          # Отключение колонтитулов

[metadata.template.header]
header-left = '\thepage'    # левый верхний колонтитул: номер страницы
header-center = ''          # центральный верхний колонтитул: пустой
header-right = '\rightmark' # правый верхний колонтитул: текущий раздел

[metadata.template.footer]
footer-left = ''            # левый нижний колонтитул: пустой
footer-center = ''          # центральный нижний колонтитул: пустой
footer-right = ''           # правый нижний колонтитул: пустой

[metadata.template.book]
book = true                 # использовать шаблон книги
# first-chapter = 28        # номер первой главы


[metadata.latex]
header-includes = '''
header-includes: |
    \usepackage{caption}
    \usepackage{sectsty}
    \sectionfont{\clearpage}
'''                         # Дополнительные включения в заголовок LaTeX

# Протестированные включения
# \usepackage[utf8]{inputenc} #может помочь, если проблема с распознаванием русского языка (вы сменили движок или шаблон)
# \usepackage[normalem]{ulem} #может понадобиться для caption, но в этом шаблоне эта строка уже включена
# \usepackage{caption} #пакет для подписей к рисункам
# \captionsetup[figure]{labelformat=empty}  # Настройка подписей к рисункам(выключить "рис. N:")
# \captionsetup[table]{labelformat=empty}  # Настройка подписей к таблицам(выключить "табл. N:")
# \usepackage{sectsty}  # Пакет для настройки стилей секций
# \sectionfont{\clearpage}  # Каждая секция с новой страницы
# \RedeclareSectionCommand[
#   beforeskip=-10pt plus -2pt minus -1pt,
#     afterskip=1sp plus -1sp minus 1sp]{paragraph}  # Настройка отступов параграфов
# \RedeclareSectionCommand[
#     beforeskip=-10pt plus -2pt minus -1pt,
#     afterskip=1sp plus -1sp minus 1sp,
#     indent=0pt]{subparagraph}  # Настройка отступов подпараграфов
# \exhyphenpenalty=10000 #запрет переноса строк для верстальщика. Отключение этих двух строк помогает, если в блоках кода слишком длинные строки не переносятся.
# \hyphenpenalty=10000 #
